### ISSUE TITLE
Cannot start iaf-example

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/frank-runner#83]
When I went to `specials/iaf-example` and ran `restart.bat`, I got the following error:

```
[ERROR] Failed to execute goal org.projectlombok:lombok-maven-plugin:1.18.20.0:delombok (default) on project frankframework-commons: Unable to delombok: InvocationTargetException: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
```

I checked that I could built my F!F checkout on the command line without the Frank!Runner. I had a checkout of the Frank!Framework as a brother directory of the Frank!Runner checkout.

**Comment by jacodg** [comment]
https://github.com/wearefrank/frank-runner/commit/7b6be7de794214560addade9adfc8dcabdf7c0ae
