### ISSUE TITLE
Frank Pipeline failure  

### ISSUE THREAD

**Issue by jplreddy** [wearefrank/frank-runner#94]
Hi Team,

Frank deployment pipeline is failing for Party Group, attached the snapshot for error details
![PipelineIssue](https://github.com/wearefrank/frank-runner/assets/166021310/42297931-70d9-4f24-bdc5-a2a7a7250e4d)

**Comment by jacodg** [comment]
This is not Frank!Runner related. Sounds more like a second or third line support question.
