### ISSUE TITLE
 Enlistment of Pooled Session into transaction failed

### ISSUE THREAD

**Issue by AH08BV** [wearefrank/frank-runner#95]
Hi frank team,

For one of our frank service, the flow is interrupted due to below error.

nl.nn.adapterframework.core.PipeRunException: Pipe [CallPushPolicy_1] caught exception: could not create Session: (JMSException) Enlistment of Pooled Session into transaction failed
at nl.nn.adapterframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:496)

 As per error, it is not able to create new session. We are not sure why it is happening. Can you please help.

**Comment by jacodg** [comment]
This is not related to Frank!Runner. Sounds like you need commercial support. In that case please visit https://wearefrank.nl/contact
