### ISSUE TITLE
specials/ladybug with test.with.iaf=true: Unnecessary download of F!F from Nexus

### ISSUE THREAD

**Issue by mhdirkse** [wearefrank/frank-runner#97]
When you run frank-runner/specials/ladybug/restart.bat with in build.properties the line `test.with.iaf=true`, then the F!F is still downloaded from Nexus. This causes a longer build time than needed.

**Comment by jacodg** [comment]
https://github.com/wearefrank/frank-runner/commit/e111b31d4508d6aaf8d5a5396479979f3b4f379c
