### ISSUE TITLE
seems like the frankdoc stays on the original version after switching to e new FF version

### ISSUE THREAD

**Issue by jjansenvr** [wearefrank/frank-runner#99]
Could be FrankFramework issue but just to be sure

I was using the frank framework ff.7.9.3 , I upgraded to 8.1.0 but my frankdoc is still showing 7.9.3 as a version

reporter: jjansenvr

**Comment by jjansenvr** [comment]
Yes this helps

**Comment by jacodg** [comment]
https://github.com/frankframework/frank-doc/pull/191
